package com.google.android.gms.common.api.internal;

import android.support.annotation.NonNull;

import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultStore;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.TransformedResult;
import com.google.android.gms.common.internal.Hide;

import java.util.concurrent.TimeUnit;

/* compiled from: OptionalPendingResultImpl */
public final class zzcp<R extends Result> extends OptionalPendingResult<R> {
    private final BasePendingResult<R> zza;

    public zzcp(PendingResult<R> pendingResult) {
        if (pendingResult instanceof BasePendingResult) {
            this.zza = (BasePendingResult) pendingResult;
            return;
        }
        throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }

    public final boolean isDone() {
        return this.zza.zze();
    }

    public final R get() {
        if (isDone()) {
            return await(0, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    public final R await() {
        return this.zza.await();
    }

    public final R await(long j, TimeUnit timeUnit) {
        return this.zza.await(j, timeUnit);
    }

    public final void cancel() {
        this.zza.cancel();
    }

    public final boolean isCanceled() {
        return this.zza.isCanceled();
    }

    public final void setResultCallback(ResultCallback<? super R> resultCallback) {
        this.zza.setResultCallback(resultCallback);
    }

    public final void setResultCallback(ResultCallback<? super R> resultCallback, long j, TimeUnit timeUnit) {
        this.zza.setResultCallback(resultCallback, j, timeUnit);
    }

    public final void store(ResultStore resultStore, int i) {
        this.zza.store(resultStore, i);
    }

    @Hide
    public final void zza(PendingResult.zza zza2) {
        this.zza.zza(zza2);
    }

    @NonNull
    public final <S extends Result> TransformedResult<S> then(@NonNull ResultTransform<? super R, ? extends S> resultTransform) {
        return this.zza.then(resultTransform);
    }

    @Hide
    public final void zzb(int i) {
        this.zza.zzb(i);
    }

    @Hide
    public final Integer zzb() {
        return this.zza.zzb();
    }
}
